/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RiddleRiddleIdRouteImport } from './routes/riddle/$riddleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiddleRiddleIdRoute = RiddleRiddleIdRouteImport.update({
  id: '/riddle/$riddleId',
  path: '/riddle/$riddleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/riddle/$riddleId': typeof RiddleRiddleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/riddle/$riddleId': typeof RiddleRiddleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/riddle/$riddleId': typeof RiddleRiddleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/riddle/$riddleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/riddle/$riddleId'
  id: '__root__' | '/' | '/riddle/$riddleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RiddleRiddleIdRoute: typeof RiddleRiddleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riddle/$riddleId': {
      id: '/riddle/$riddleId'
      path: '/riddle/$riddleId'
      fullPath: '/riddle/$riddleId'
      preLoaderRoute: typeof RiddleRiddleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RiddleRiddleIdRoute: RiddleRiddleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
